/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Gestion_Restau (void);
GtkWidget* create_Gestion_Capteur (void);
GtkWidget* create_acceuilw (void);
GtkWidget* create_gestionw (void);
GtkWidget* create_dialog_service_partie_2 (void);
GtkWidget* create_afficher_et (void);
GtkWidget* create_ajouter_et (void);
GtkWidget* create_Modifier_et (void);
GtkWidget* create_supprimer_et (void);
GtkWidget* create_non (void);
GtkWidget* create_window_stock (void);
GtkWidget* create_oui (void);
